### PR TITLE
Add type name for additional debug info

### PR DESCRIPTION
**Pull request by ChandlerSwift**

### CODE REVIEW

**Comment by ChandlerSwift** [comment]
Looks like it fails the Python 3.5 test because I used an f-string. Python 3.5 is out of support, so I'd be happy to either remove that from the .travis.yml file, or switch out the f-string for something else.

**Comment by derpferd** [comment]
Go ahead and remove Python 3.5.

**Comment by ChandlerSwift** [comment]
Should be done in #16.

**Comment by derpferd** [comment]
@ChandlerSwift Merged #16 rebasing this branch should fix the error with `3.5`

**Comment by ChandlerSwift** [comment]
Rebased. Tests are looking good so far (Travis hasn't finished at time of writing). Anything else I should be fixing?

**Pull request merged**
